#!/bin/bash


# Stop when error
set -e

# System check
#

# Colors
source ./utils/colors

# Default values
export ESTATE_DIR=/srv/estate
APPS_DIR=/srv/apps
INC_DIR=inc
QUIET_LOGS=1

# Check $ESTATE_DIR folder exist

# Create $APPS_DIR folder if not exist
#mkdir -p "$APPS_DIR"

if [ -z "${QUIET_LOGS:-}" ]; then
    exec 3>&1
else
    exec 3>/dev/null
fi



if /usr/bin/find "$INC_DIR" -mindepth 1 -maxdepth 1 -type f -print -quit 2>/dev/null | read v; then
    echo >&3 "$0: $INC_DIR is not empty, will attempt to perform configuration"

    echo >&3 "$0: Looking for shell scripts in $INC_DIR"
    find "$INC_DIR" -follow -type f -print | sort -V | while read -r f; do
        case "$f" in
            *.sh)
                if [ -x "$f" ]; then
                    echo >&3 "$0: Launching $f";
                    "$f"
                else
                    # warn on shell scripts without exec bit
                    echo >&3 "$0: Ignoring $f, not executable";
                fi
                ;;
            *) echo >&3 "$0: Ignoring $f";;
        esac
    done

    echo >&3 "$0: Configuration complete; ready for start up"
else
    echo >&3 "$0: No files found in $INC_DIR, skipping configuration"
fi



echo "[Success] Project created"