#!/bin/bash

# Stop when error
set -e

# System check
#

# Default values
ESTATE_DIR=/srv/estate
APPS_DIR=/srv/apps

# Check $ESTATE_DIR folder exist

# Create $APPS_DIR folder if not exist
mkdir -p "$APPS_DIR"


echo "[Success] Project created"